#!/bin/bash

############################################################################
#
# 本定制工具完全免费，由DsiXDA开发，由“半指遮天”完成汉化翻译。
#
#     我的新浪微博：      http://weibo.com/hqapk
#     我的腾讯微博：      http://t.qq.com/hqapkcom
#
############################################################################

version=0.225


if [ ! -e menu ]
then
  echo
  echo "       = 提醒 =       "
  echo "----------------------------------------------------"
  echo "  确保你是从其所在的文件夹中运行此文件安装，"
  echo "  否则厨房运行时将出现问题脚本, 打开厨房时请"
  echo "  使用 ./menu 命令运行厨房,不要尝试其他命令或方法!"
  echo ""
  exit 0
fi

dir_list=( original_update scripts tools )
error_found=0

for check_dir in ${dir_list[@]}
do
  if [ ! -e $check_dir ]
  then
    echo "错误提示:'$check_dir'文件夹找不到"
    error_found=1
  fi
done

if [ $error_found == 1 ]
then
  echo "       = 提醒 =       "
  echo "----------------------------------------------------"
  echo "  请确保你已正确安装了厨房文件夹."
  exit 0
fi


chmod 755 scripts/*
scripts/check_install_dir

if [ "$?" == "1" ]
then
  exit 0
fi

scripts/init_kitchen
scripts/check_binaries

if [ "$?" == "1" ]
then
  exit 0
fi


while :
do

  clear

  echo "============================================================"
  echo "     Android Kitchen  厨房定制工具     V0.225  BY 半指遮天  "
  echo "============================================================"
  echo "    论坛地址 ：bbs.hqapk.com  ｜    技术支持  ：云卓论坛    "
  echo "============================================================"
  echo "    最新版本请关注我的新浪微博：http://weibo.com/hqapk      "
  echo "============================================================"
  echo "> 基础选项"
  echo
  echo "  1 - 导入 ROM 文件到工作文件夹 （ 分解ROM包 ） "
  echo "  2 - 添加 Root 最高权限"
  echo "  3 - 添加 BusyBox 指令集"
  echo "  4 - 关闭开机画面音乐"
  echo "  5 - 对所有 Apk 文件进行 Zipalign 操作，优化内存占用 "
  echo "  6 - 更改 ROM 的 Wipe 操作状态"
  echo "  7 - 更改 ROM 显示名称"
  echo "  8 - 显示工作文件夹信息"
  echo 
  echo "  0 - 高级选项菜单"
  echo " 00 - 传统选项（较少使用的选项）菜单"
  echo " 99 - 从工作文件夹建立 ROM 刷机包"
  echo
  echo "  u - 更新/关于厨房"
  echo "  x - 退出"
  echo -n " 请输入选择项: "
  read opt

  if [ "$opt" != "x" ] && [ "$opt" != "u" ] && [ "$opt" != "1" ]
  then
    scripts/check_multiple_working
  fi
  
  if [ "$?" != "1" ]
  then
    case $opt in
      1) clear; scripts/check_rom; continue;;
      2) scripts/do_root; continue;;
      3) scripts/add_busybox show_help;;
      4) scripts/disable_sounds;;
      5) scripts/do_zipalign;;
      6) scripts/change_wipe;;
      7) scripts/change_rom_name;;
      8) scripts/show_rom_info;;
      0) scripts/menu_advanced $version; continue;;
      00) scripts/menu_legacy $version; continue;;
      99) scripts/build_rom;;
      u) scripts/about $version; continue;;
      x) scripts/init_kitchen; clear; echo; echo "欢迎再次使用“半指遮天”汉化的厨房工具，祝您定制、刷机愉快，再见！"; echo; exit 1;;
      *) echo " 错误选择项"; continue;;
    esac
  fi

  scripts/press_enter

done

